README.md
lib/identity-idp-functions/version.rb
source/proof_address/lib/proof_address.rb
source/proof_address/spec/proof_address_spec.rb

This should make it easier to share code with development mode and in specs, when we can't necessarily POST to a webhook URL

Add block form for local development

---

README.md
lib/identity-idp-functions.rb
lib/identity-idp-functions/demo_function.rb
lib/identity-idp-functions/proof_address.rb
lib/identity-idp-functions/version.rb
source/demo_function/spec/demo_function_spec.rb
source/proof_address/spec/proof_address_spec.rb
spec/identity-idp-functions_spec.rb

**Why**: The IDP doesn't load some of the gem dependencies in the test
environment, so eagerly loading those functions results in an error
I ran into errors in test in https://github.com/18F/identity-idp/pull/4264, so hopefully merging this will allow me to fix those

Switch to explicit/lazy requires

---

source/template.yaml

Deployment pipeline is failing for Lambda functions.  Typo in function list.

Fix typo and remove duplicate function from list

---

lib/identity-idp-functions/version.rb
source/proof_address/lib/proof_address.rb
source/proof_address/spec/proof_address_spec.rb
source/proof_address_mock/lib/proof_address_mock.rb
source/proof_address_mock/spec/proof_address_mock_spec.rb
source/proof_resolution/lib/proof_resolution.rb
source/proof_resolution/spec/proof_resolution_spec.rb
source/proof_resolution_mock/lib/proof_resolution_mock.rb
source/proof_resolution_mock/spec/proof_resolution_mock_spec.rb

**Why**: It gets triggered in "local" mode when we call
this inline from the IDP, but at that point the env variable
will not be there
Also updates mock functions to fetch because they need the
parameter as well

Remove eager ENV.fetch

---

.circleci/config.yml

I noticed that the step to upload to S3 happened before we ran the local RSpec tests, so I tried flipping that around
Also, do we want to add a filter to the upload step to S3 uploads only happen from the `master` branch?

Update CircleCI to run RSpec first before uploading lambdas

---

source/template.yaml

AWS prevents securestrings from being used as environment variables in Lambda functions.

Remove proof token environment vars

---

source/buildspec.yml

Don't fail the deployment pipeline if the sam deploy returns an empty changeset.  May need to rerun pipeline and don't want the pipeline to show failed state.

Don't fail deploy pipeline if empty changeset

---

.circleci/config.yml
source/template.yaml

Update CircleCi to only copy to S3 when building the master branch Issue https://github.com/18F/identity-devops/issues/2973
Copy template to prod lambda s3 bucket 
Set function names instead of using SAM template default name

Updates to SAM template and CircleCi config

---

lib/identity-idp-functions/version.rb
source/template.yaml

Temporarily allow traffic outbound to proxy server on port 3128 until api is available on vpc.

Allow outbound to proxy

---

lib/identity-idp-functions.rb
source/aws-ruby-sdk/faraday_helper.rb
source/aws-ruby-sdk/ssm_helper.rb
source/proof_address/lib/proof_address.rb
source/proof_address_mock/lib/proof_address_mock.rb
source/proof_resolution/lib/proof_resolution.rb
source/proof_resolution_mock/lib/proof_resolution_mock.rb

- Shorter timeouts make things easier to debug

Add shorter connection timeouts to Faraday, AWS::SSM::Client

---

lib/identity-idp-functions.rb
lib/identity-idp-functions/version.rb
source/aws-ruby-sdk/error_helper.rb
source/aws-ruby-sdk/errors.rb
source/aws-ruby-sdk/function_helper.rb
source/proof_address/lib/proof_address.rb
source/proof_address/spec/proof_address_spec.rb
source/proof_address_mock/lib/proof_address_mock.rb
source/proof_address_mock/spec/proof_address_mock_spec.rb
source/proof_resolution/lib/proof_resolution.rb
source/proof_resolution/spec/proof_resolution_spec.rb
source/proof_resolution_mock/lib/proof_resolution_mock.rb
source/proof_resolution_mock/spec/proof_resolution_mock_spec.rb
spec/shared_examples_for_proofers.rb

This addresses the case where the lambda could make a call to the vendor despite not being able to make the callback to the IDP

raise error if auth token is blank and block not given (LG-3683)

---

.circleci/config.yml
.rspec
lib/identity-idp-functions/version.rb
source/proof_address/lib/proof_address.rb
source/proof_address_mock/lib/proof_address_mock.rb
source/proof_resolution/lib/proof_resolution.rb
source/proof_resolution_mock/lib/proof_resolution_mock.rb

We had an error in prod due to a sneaky ActiveSupport implicit dependency:
```
{
"errorMessage": "undefined method `present?' for \"f7b7714de17eeee6ba026e1e451ee579\":String\nDid you mean?  prepend",
"errorType": "Function<NoMethodError>",
"stackTrace": [
"/var/task/proof_resolution_mock.rb:27:in `proof'",
"/var/task/proof_resolution_mock.rb:15:in `handle'"
]
}
```
Our test process does load ActiveSupport so this does sneaked through CI
I removed the load-all in `.rspec` which lets us run individual specs and catch this next time

Fix implicit ActiveSupport dependency

---

lib/identity-idp-functions/version.rb
source/aws-ruby-sdk/faraday_helper.rb
source/proof_address/spec/proof_address_spec.rb
source/proof_address_mock/spec/proof_address_mock_spec.rb
source/proof_resolution/spec/proof_resolution_spec.rb
source/proof_resolution_mock/spec/proof_resolution_mock_spec.rb
spec/shared_examples_for_proofers.rb

I discovered that 401's from the IDP were considered successful lambda runs.... which is incorrect

Error on 4XX or 5XX errors from the IDP

---

.rubocop.yml
lib/identity-idp-functions/version.rb
source/aws-ruby-sdk/function_helper.rb
source/aws-ruby-sdk/logging_helper.rb
source/aws-ruby-sdk/timer.rb
source/proof_address/lib/proof_address.rb
source/proof_address/spec/proof_address_spec.rb
source/proof_address_mock/lib/proof_address_mock.rb
source/proof_resolution/lib/proof_resolution.rb
source/proof_resolution/spec/proof_resolution_spec.rb
source/proof_resolution_mock/lib/proof_resolution_mock.rb
source/proof_resolution_mock/spec/proof_resolution_mock_spec.rb
spec/lib/logging_helper_spec.rb
spec/lib/timer_spec.rb
spec/spec_helper.rb

This adds:
- JSON-formatted logging to our lambdas (to STDOUT), matches `events.log` format in the IDP
- Logging of trace IDs (assuming we pass an explicit `trace_id` param from the IDP)
- Timing information for talking to vendors
- If we have to retry, do we want to log each call separately? For now, no
Is there anything else we want to log?
I need to do a thorough second pass to make sure I instrumented all 4 lambdas right, but this is a first pass 
Example log lines:
```json
{"name":"ProofResolutionMock","trace_id":"b1f39e38-4dd0-451a-9be7-11ff1625f1e2","success":true,"timing":{"callback":10.37},"time":"2020-11-19T17:51:25-08:00","level":"INFO"}
{"name":"ProofResolution","trace_id":"c9b2ee50-aa37-4bb4-992b-14cfad17f831","resolution_success":true,"state_id_success":true,"timing":{"resolu …
```

Logging, Timing, Tracing

---

source/template.yaml.erb

we get warnings like these:
```
/var/lang/lib/ruby/2.7.0/net/http.rb:1122: warning: The environment variable HTTP_PROXY is discouraged.  Use http_proxy.
/var/lang/lib/ruby/2.7.0/net/http.rb:1122: warning: The environment variable HTTP_PROXY is discouraged.  Use http_proxy.
/var/lang/lib/ruby/2.7.0/net/http.rb:1122: warning: The environment variable HTTP_PROXY is discouraged.  Use http_proxy.
```
See source @ https://github.com/ruby/ruby/blob/master/lib/uri/generic.rb#L1474-L1489

Use lowercase env vars so that Ruby's Net::HTTP doesn't warn

---

Gemfile
lib/identity-idp-functions/version.rb
source/proof_document/lib/Gemfile
source/proof_document_mock/lib/Gemfile

Ahead of updating to make the doc verification async, to match https://github.com/18F/identity-idp/pull/4461

Update identity-doc-auth version

---

lib/identity-idp-functions/version.rb
source/aws-ruby-sdk/s3_helper.rb
source/proof_document/lib/proof_document.rb
source/proof_document/spec/proof_document_spec.rb
source/proof_document_mock/lib/proof_document_mock.rb
source/proof_document_mock/spec/proof_document_mock_spec.rb
spec/lib/s3_helper_spec.rb

The "plain" HTTP get This is only for the mock proofer, and only for local development and test cases
The Base64 changes are needed for both normal and mock proofers

Update mock document proofer to be able to substitute local URLs for S3

---

source/aws-ruby-sdk/encryption_helper.rb
source/proof_document_mock/spec/proof_document_mock_spec.rb
spec/lib/encryption_helper_spec.rb
spec/support/encryption.rb

As I'm cleaning up https://github.com/18F/identity-idp/pull/4464, I realized I wanted this method and didn't want to reimplement it

Move encrypt method onto EncryptionHelper so we can use it downstream

---

lib/identity-idp-functions/version.rb
source/proof_document/lib/proof_document.rb
source/proof_document/spec/proof_document_spec.rb
source/proof_document_mock/lib/proof_document_mock.rb
source/proof_document_mock/spec/proof_document_mock_spec.rb

**Why**: GetResultsResponse#to_h (from identity-doc-auth)
intentionally excludes to prevent accidental logging
@aduth's comment (https://github.com/18F/identity-idp/pull/4464#discussion_r531635394) prompted me to check in why we weren't receiving PII, and the answer was because we exclude PII from `#to_h` intentionally: https://github.com/18F/identity-doc-auth/blob/ac9f43820717343788ea6e0dfb9f75f8ec610f8d/lib/identity_doc_auth/acuant/responses/get_results_response.rb#L27-L40

Make sure to send pii_from_doc in ProofDocument, ProofDocumentMock

---

source/aws-ruby-sdk/s3_helper.rb
source/proof_document/lib/Gemfile
source/proof_document_mock/lib/Gemfile

- Also make gem require lazy, because we load the helpers
in every single function, even the ones that don't need S3
Error in deployed env:
```
{
"errorMessage": "cannot load such file -- aws-sdk-s3",
"errorType": "Init<LoadError>",
"stackTrace": [
"/opt/ruby/lib/s3_helper.rb:1:in `require'",
"/opt/ruby/lib/s3_helper.rb:1:in `<top (required)>'",
```
because the `ProofDocument` function didn't specify s3 as a dependency (even though `aws-sdk-ruby` did)

Move S3 dependency into individual functions

---

lib/identity-idp-functions/version.rb

This is my guess at fixing async... maybe the previous SHA on `main` just didn't make it through the pipeline (the build was flakey yesterday), so I want to see if just generating a new one will do the trick

Empty version bump to generate a new SHA

---

source/template.yaml.erb

Update security group to allow traffic on port 443 to the vpc.
Tested ProofAddressMockFunction was able to reach IDP server.
```
START RequestId: 219c1ec1-633b-4be2-964d-9330e1524a7a Version: $LATEST
{"name":"ProofAddressMock","trace_id":null,"success":true,"timing":{"address":0.08,"callback":316.97},"time":"2021-02-02T21:08:27+00:00","level":"INFO"}
Error raised from handler method{
"errorMessage": "the server responded with status 404",
"errorType": "Function<Faraday::ResourceNotFound>",
"stackTrace": [
"/var/task/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/response/raise_error.rb:22:in `on_complete'",
"/var/task/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:19:in `block in call'",
"/var/task/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/resp …
```

All TCP port 443 traffic to vpc

---

Gemfile
identity-idp-functions.gemspec
lib/identity-idp-functions/version.rb
source/proof_resolution/lib/Gemfile
source/proof_resolution/lib/proof_resolution.rb
source/proof_resolution/spec/proof_resolution_spec.rb
source/proof_resolution_mock/lib/proof_resolution_mock.rb
source/proof_resolution_mock/lib/resolution_mock_client.rb
source/proof_resolution_mock/lib/state_id_mock_client.rb
source/proof_resolution_mock/spec/proof_resolution_mock_spec.rb

- Updates to send transaction_id for lexisnexis, aamva separately
- Updates mock proofer to send transaction_id as well

Include transaction_id from AAMVA (LG-4257)

---

lib/identity-idp-functions/version.rb
source/proof_address/lib/proof_address.rb
source/proof_address/spec/proof_address_spec.rb
source/proof_address_mock/lib/address_mock_client.rb
source/proof_address_mock/lib/proof_address_mock.rb
source/proof_address_mock/spec/proof_address_mock_spec.rb

Similar to: #60
**Why**: So that downstream logging includes conversation ID from LexisNexis address proofing result.

LG-4265: Include transaction ID in address result

---

Gemfile
identity-idp-functions.gemspec
lib/identity-idp-functions/version.rb
source/doc_auth_layer/errors.rb
source/proof_address/lib/proof_address.rb
source/proof_address_mock/lib/proof_address_mock.rb
source/proof_resolution/lib/Gemfile
source/proof_resolution/lib/proof_resolution.rb
source/proof_resolution/spec/proof_resolution_spec.rb
source/proof_resolution_mock/lib/proof_resolution_mock.rb
source/proof_resolution_mock/spec/proof_resolution_mock_spec.rb

- For local invocation, adds an :aamva_config to the job 
Will make a PR to update Lambda::Runner in the IDP as well to handle this

Update AAMVA gem to use explicit configuration
